"""Portions generated by AI with human review.

Command-line entry point for map generation."""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path
from typing import Dict, Any

import yaml

from .generate import export_dataset, generate_world, render_png
from .core.tectonics import generate_tectonic_field, save_tectonic_field


def load_config(path: str | None) -> Dict[str, Any]:
    if not path:
        return {}
    with open(path, "r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    if not isinstance(data, dict):
        msg = f"Config must be a mapping, got {type(data).__name__}"
        raise ValueError(msg)
    return data


def main() -> None:
    parser = argparse.ArgumentParser("map_maker")
    parser.add_argument("--width", type=int, default=512)
    parser.add_argument("--height", type=int, default=512)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--config", type=str, default=None, help="YAML config file")
    parser.add_argument("--out", type=str, default="out/map.png")
    parser.add_argument(
        "--render-mode",
        type=str,
        default="elevation",
        choices=["elevation", "biome"],
        help="Map rendering style",
    )
    parser.add_argument(
        "--dataset-dir",
        type=str,
        default=None,
        help="Optional path to write GeoTIFF/Parquet interchange data",
    )
    parser.add_argument(
        "--tectonics-out",
        type=str,
        default=None,
        help="Optional NPZ sidecar for tectonic fields",
    )
    parser.add_argument(
        "--tectonics-plates",
        type=int,
        default=None,
        help="Override number of tectonic plates (default uses config or 12)",
    )
    args = parser.parse_args()

    config = load_config(args.config)

    t0 = time.time()
    world = generate_world(width=args.width, height=args.height, seed=args.seed, config=config)
    image = render_png(world, mode=args.render_mode)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    image.save(out_path)

    metadata = {
        "seed": args.seed,
        "width": args.width,
        "height": args.height,
        "config": config,
        "stats": world["stats"],
        "render_mode": args.render_mode,
    }
    with open(out_path.with_suffix(".json"), "w", encoding="utf-8") as fh:
        json.dump(metadata, fh, indent=2)

    if args.dataset_dir:
        export_dataset(args.dataset_dir, args.seed, world)
        metadata.setdefault("sidecars", {})["dataset"] = str(Path(args.dataset_dir))

    if args.tectonics_out:
        tect_cfg = config.get("tectonics", {}) if isinstance(config, dict) else {}
        num_plates = args.tectonics_plates or int(tect_cfg.get("num_plates", 12))
        wrap_x = bool(tect_cfg.get("wrap_x", False))
        wrap_y = bool(tect_cfg.get("wrap_y", False))
        field = generate_tectonic_field(
            width=args.width,
            height=args.height,
            seed=args.seed,
            num_plates=num_plates,
            wrap_x=wrap_x,
            wrap_y=wrap_y,
        )
        save_tectonic_field(field, args.tectonics_out)
        out_path = Path(args.tectonics_out)
        arrays_path = out_path if out_path.suffix else out_path.with_suffix(".npz")
        metadata.setdefault("sidecars", {})["tectonics"] = {
            "path": str(arrays_path),
            "metadata": field.metadata,
        }

    elapsed = time.time() - t0
    extras = []
    if args.dataset_dir:
        extras.append(f"dataset in {Path(args.dataset_dir)}")
    if args.tectonics_out:
        extras.append(f"tectonics sidecar {Path(args.tectonics_out)}")
    extras_str = f" ({', '.join(extras)})" if extras else ""
    print(
        f"Wrote {out_path} and {out_path.with_suffix('.json')}{extras_str} in {elapsed:.2f}s"
    )


if __name__ == "__main__":
    main()
