"""Portions generated by AI with human review.

Command-line entry point for map generation."""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path
from typing import Dict, Any

import yaml

from map_maker.generate import export_dataset, generate_world, render_png


def load_config(path: str | None) -> Dict[str, Any]:
    if not path:
        return {}
    with open(path, "r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    if not isinstance(data, dict):
        msg = f"Config must be a mapping, got {type(data).__name__}"
        raise ValueError(msg)
    return data


def main() -> None:
    parser = argparse.ArgumentParser("map_maker")
    parser.add_argument("--width", type=int, default=512)
    parser.add_argument("--height", type=int, default=512)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--config", type=str, default=None, help="YAML config file")
    parser.add_argument("--out", type=str, default="out/map.png")
    parser.add_argument(
        "--render-mode",
        type=str,
        default="elevation",
        choices=["elevation", "biome"],
        help="Map rendering style",
    )
    parser.add_argument(
        "--dataset-dir",
        type=str,
        default=None,
        help="Optional path to write GeoTIFF/Parquet interchange data",
    )
    args = parser.parse_args()

    config = load_config(args.config)

    t0 = time.time()
    world = generate_world(width=args.width, height=args.height, seed=args.seed, config=config)
    image = render_png(world, mode=args.render_mode)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    image.save(out_path)

    metadata = {
        "seed": args.seed,
        "width": args.width,
        "height": args.height,
        "config": config,
        "stats": world["stats"],
        "render_mode": args.render_mode,
    }
    with open(out_path.with_suffix(".json"), "w", encoding="utf-8") as fh:
        json.dump(metadata, fh, indent=2)

    if args.dataset_dir:
        export_dataset(args.dataset_dir, args.seed, world)

    elapsed = time.time() - t0
    extras = []
    if args.dataset_dir:
        extras.append(f"dataset in {Path(args.dataset_dir)}")
    extras_str = f" ({', '.join(extras)})" if extras else ""
    print(
        f"Wrote {out_path} and {out_path.with_suffix('.json')}{extras_str} in {elapsed:.2f}s"
    )


if __name__ == "__main__":
    main()
